### ISSUE TITLE
Unexpected error

### ISSUE THREAD

**Issue by laurapeeters** [guntervs/weareimd-drupal8#11]
Na het installeren van een module kreeg ik deze foutmelding "The website encountered an unexpected error. Please try again later". Valt dit op één of andere manier op te lossen?

**Comment by guntervs** [comment]
Welke module probeerde je te installeren?

**Comment by laurapeeters** [comment]
Ik weet niet juist aan dewelke het heeft gelegen want ik had er een paar tegelijkertijd geïnstalleerd. Ik ben ondertussen al opnieuw begonnen want ik kreeg het niet opgelost en verloor te veel tijd... Ik had nog wel een vraagje over het Nexus theme, u had een oplossing gepost op facebook voor het probleem met de image slider maar deze lijkt niet te werken, ook niet bij anderen uit de klas.

**Comment by guntervs** [comment]
Bij Laura Van Bael is het uiteindelijk wel gelukt. Heb je daar al eens gehoord?

Caches leeggemaakt nadat je die fix hebt toegepast?
