### ISSUE TITLE
GuzzleHttp\Exception\RequestException: cURL error 77

### ISSUE THREAD

**Issue by r0615219** [guntervs/weareimd-drupal8#12]
Zou iemand mij kunnen helpen? Ik probeer via Guzzle een api te lezen. Maar ik krijg steeds een error over een certificaat dat niet in orde is : 

The website encountered an unexpected error. Please try again later.

GuzzleHttp\Exception\RequestException: cURL error 77: error setting certificate verify locations: CAfile: C:\Program Files (x86)\DevDesktop\common\cert\cacert.pem CApath: none (see http://curl.haxx.se/libcurl/c/libcurl-errors.html) in GuzzleHttp\Handler\CurlFactory::createRejection() (line 187 of vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php).

**Comment by guntervs** [comment]
@r0615219, kan je je code ook laten zien? Welke API probeer je aan te spreken?

**Comment by r0615219** [comment]
Ik probeer te werken met de api van bandsintown : https://rest.bandsintown.com/artists/Coldplay?app_id=bandsintowncms.

Mijn code : 
BandsintownClient.php : http://puu.sh/wcoy6/1dee54c51f.png
BandsController.php : http://puu.sh/wcoAM/901df85e8b.png

**Comment by guntervs** [comment]
Hi,
Voeg na regel 26 in je Client eens volgende lijn code toe:
`$this->client->setDefaultOption('verify', false);`

Dit is niet iets wat je irl zou mogen doen, maar voor je huidig probleem gaat dit wel een dirty fix zijn.

Het komt erop neer dat er lokaal gezocht wordt naar een certificaat, maar hij vindt het niet. Je zou dit in theorie in orde moeten brengen.
