### ISSUE TITLE
Migraten

### ISSUE THREAD

**Issue by maxvranken** [guntervs/weareimd-drupal8#2]
Hoe migrate je een website van de ene laptop naar de andere? Backup and migrate tool werkt niet. De restore optie geeft een server error. 
Ook een goede tip om samen aan de css te kunnen werken?

Mvg
Max

**Comment by guntervs** [comment]
@maxvranken, ik heb een nieuw issue gemaakt voor de CSS.

De klassieke workflow:
- Databank exporteren (bvb. via phpmyadmin)
- Files kopiëren naar andere omgeving/laptop
- Databank importeren (bvb. via phpmyadmin)
- sites/default/settings.php aanpassen met de nieuwe database credentials
- host file aanpassen

Via Acquia Dev Desktop:
- Export: https://docs.acquia.com/dev-desktop/sites/backup
- Import: https://docs.acquia.com/dev-desktop/start/local
