### ISSUE TITLE
Hoe samen aan CSS werken?

### ISSUE THREAD

**Issue by guntervs** [guntervs/weareimd-drupal8#3]

**Comment by guntervs** [comment]
Samen werken = git.

Je kan ervoor kiezen om je git repository te starten in de Drupal root of in je theme. Het kan zijn dat je caches moet clearen wanneer je nieuwe code ophaalt, omdat de andere persoon bvb. iets heeft aangepast in een yml file.

Onze workflow (via command line en vereenvoudigd):

_Theme changes_
- git add themes/itr_theme (voegt alle changes in itr_theme toe aan de staging area)
- git commit -m "Commit message ivm. changes die gemaakt zijn"
- git push

_Config changes (bvb. display suite, blocks, ...)_
- drush cex -y (exporteer de huidige configuratie bvb. changes aan display suite)
- git add -A (niet 100% correct, maar goed genoeg momenteel)
- git commit -m "Commit message ivm. changes die gemaakt zijn"
- git push

_Nieuwe code binnenhalen_
- git pull
- drush cim -y (evt. nieuwe config importeren)
- drush cr (caches clearen)

_Om drush cex -y te doen werken met git, kan je best in je settings.php file de locatie van de config directory aanpassen naar sites/default/config/sync ipv sites/default/files/[random_hash]/sync_

**Comment by jorendemaeyer1996** [comment]
Zijn er bepaalde files/folder die je beter in een .gitignore kan stoppen?

**Comment by guntervs** [comment]
Je kan hier best eens voor in de example gitignore kijken van Drupal zelf. Zie ook https://gist.github.com/octocat/9257657

De folders van je IDE (bvb. .idea bij PHPStorm) best ook.
