### ISSUE TITLE
Geen style.css mogelijk

### ISSUE THREAD

**Issue by DamonBaesen** [guntervs/weareimd-drupal8#4]
Ik heb de template in de juiste map geplaatst maar wanneer ik in style.css iets aanpas krijg ik dit ook na het clearen van mijn caches nog steeds niet te zien.

**Comment by guntervs** [comment]
Damon, kan je iets meer omkadering geven? Hoe ziet je libraries file eruit? Je info file?

**Comment by DamonBaesen** [comment]
Gunter, dit staat in mij info: 
name: WeAreIMD
type: theme
description: 'The We Are IMD base theme.'
package: Core
core: 8.x
base theme: stable

libraries:
  - weareimd/default

En dit in mij libraries:
base:
  css:
    theme:
      css/style.css: {}

**Comment by guntervs** [comment]
Drop je theme hier even, want op het eerste zicht ziet het er goed uit. Ook wat je exact wil bereiken.

**Comment by DamonBaesen** [comment]
[weareimd.zip](https://github.com/guntervs/weareimd-drupal8/files/212390/weareimd.zip)
Ik wil de css aan het project doen maar wanneer ik iets basic test zie ik geen resultaat.

**Comment by DamonBaesen** [comment]
Naast dit theme heb ik ook nog steeds bootstrap-theme.

**Comment by guntervs** [comment]
Welk team is actief?

**Comment by DamonBaesen** [comment]
hoe kan ik dit nakijken?

**Comment by DamonBaesen** [comment]
WeAreIMD heb ik net gezien

**Comment by guntervs** [comment]
My bad. In de libraries heet de library base en in de info file voeg ik weareimd/default toe. Dit moet dus default zijn op beide plaatsen (of base). Net aangepast.

**Comment by DamonBaesen** [comment]
Ik heb het aangepast maar ik zie nog geen verandering :(

**Comment by guntervs** [comment]
Caches opnieuw leeggemaakt?

**Comment by DamonBaesen** [comment]
Ja.

**Comment by guntervs** [comment]
Je hebt in de info file /default aangepast naar /base of in de libraries file base: aangepast naar default: ?

**Comment by DamonBaesen** [comment]
libraries --> base naar default

**Comment by guntervs** [comment]
Stuur nog eens door als je wilt.

**Comment by DamonBaesen** [comment]
[themes.zip](https://github.com/guntervs/weareimd-drupal8/files/212452/themes.zip)

**Comment by guntervs** [comment]
Je theme pakt nu wel, maar door bootstrap dat in html.html.twig ingeladen wordt, wordt dit overschreven. Je kan dit oplossen door bootstrap uit de html template te halen of dit hoger te zetten dan je css-placeholder.

**Comment by DamonBaesen** [comment]
Hoe kan ik dit precies doen en waar ergens doen?

**Comment by guntervs** [comment]
In de html.html.twig template.

**Comment by DamonBaesen** [comment]
Oke top heb het eruit gehaald en het werkt! Bedankt voor de zeer snelle support!
