### ISSUE TITLE
Viewmode hergebruiken

### ISSUE THREAD

**Issue by MiguelIMD** [guntervs/weareimd-drupal8#5]
Hoe kun je een viewmode hergebruiken maar met andere inhoud

Bv met een andere offset

**Comment by r0604172** [comment]
Na het aanmaken van een nieuwe view mode: 
FORMAT > Show > in het 2de veld kan je aan eerder aangemaakte view mode selecteren

**Comment by guntervs** [comment]
Je bedoelt een display op een view?

Rechts boven op de view heb je een dropdown button. Je kan een display clonen. In de nieuwe display kan je zaken aanpassen, zoals de offset.
