### ISSUE TITLE
Preprocess hook & Bootstrap

### ISSUE THREAD

**Issue by lucaspoignon** [guntervs/weareimd-drupal8#6]
Dag Gunter

Christophe en ik hebben als opdracht de fubiz.net website te themen. Bij het onderdeel Must Read onderaan de pagina kan de gebruiker door middel van een exposed filter een categorie kiezen waarna er 5 artikels verschijnen.

De 5 artikels zijn verspreid over 3 kolommen, met behulp van Bootstrap. Het is ons gelukt om de twig template file te vinden die gelinkt is aan onze block view.

Link naar screenshot: http://imgur.com/bjxC9z0

Ons probleem:

1. We kunnen {{ dump() }} niet gebruiken om alle bruikbare variabelen te tonen. Dit geeft ons een volledig wit scherm.

2. {{ content }} geeft ons de volledige content van de block. Het lukt ons niet om de inhoud van één artikel aan te spreken en dit bv. in een bootstrap kolom te zetten. Onze eerste gedachte is dat de inhoud van deze variabele door middel van een for each lus gegenereerd is. Is het mogelijk om de inhoud in aparte variabelen te steken? Al ons onderzoek stuurt ons richting preprocess functies.

3. 

@see bootstrap_preprocess_block()
 * @see template_preprocess()
 * @see template_preprocess_block()
 * @see bootstrap_process_block()
 * @see template_process()

Deze code staat in de twig template file. In de cursus staat ergens vermelding van een file die je themanaam.theme moet noemen en dat je hierin deze preprocess functies kan overschrijven. Welke van de 5 bovenvermelde hooks zouden we in dit geval nodig hebben. Kunnen we in deze hook een for each lus gebruiken en deze in verschillende variabelen steken?

Wij hopen dat je ons in de goede richting kan wijzen :)

**Comment by guntervs** [comment]
Block gaat een niveau te hoog zijn. Om extra classes toe te voegen, zal je eerder een view template moeten overschrijven. Dit hebben we niet gezien, daarom enkele alternatieven.

De eenvoudigste manier om dit block te maken is om bij format te kiezen voor display suite en een alternerende view mode te selecteren (bvb. 1,2,4 en 5 krijgen teaser, 3 krijgt highlight).

Een shortcut zou zijn om 3 displays te maken en met offset te werken.

**Comment by lucaspoignon** [comment]
Ok. We zullen dit eens proberen.

Met je tweede voorstel bedoel je 3 block views aanmaken, en die via css naast elkaar zetten? Hoe kan je hier die exposed filter integreren?

**Comment by guntervs** [comment]
Klopt. Voor de exposed filter zou je eventueel met een attachment kunnen werken als display ipv. blocks.

Dus 1 block met 2 attachments. Attachments erven exposed filters over.

Zoals je ziet, meerdere oplossingen voor dit probleem. De exposed filter is ook niet het belangrijkste.
