### ISSUE TITLE
Regions stable-theme

### ISSUE THREAD

**Issue by DamonBaesen** [guntervs/weareimd-drupal8#7]
Om een extra region te kunnen creeëren moet ik al de regions kennen die de template stable gebruikt daar de weareimd template hierop gebasseerd is want wanneer ik bij de info.yml van weareimd een nieuwe region creer verdwijnen al de andere omdat je die niet aanroept. 
Ik kan jammer genoeg bij de info.yml van stable niets vinden in verband met regions. Weet u misschien waar ik deze nog kan terugvinden? Alvast bedankt!!

**Comment by guntervs** [comment]
Default regions vind je in de documentatie van page.html.twig: https://api.drupal.org/api/drupal/core%21modules%21system%21templates%21page.html.twig/8

**Comment by DamonBaesen** [comment]
Kan je deze zomaar verwijderen uit stable of mag dit niet?

**Comment by guntervs** [comment]
De enige verplichte region is "content".

**Comment by DamonBaesen** [comment]
ik heb nu uit de stable page.html.twig de sidebarFirst and sidebarSecond verwijdert en na het clearen van de caches blijven deze toch staan. Is er nog iets dat je hiervoor moet doen?

**Comment by guntervs** [comment]
Hoe heb je deze verwijderd?

**Comment by DamonBaesen** [comment]
uit de page.html die twee regios gedeleted

**Comment by guntervs** [comment]
Een regio verwijderen uit een template != een regio verwijderen uit het systeem.

Regio's worden gedefinieerd in code. Welke regio's dit zijn vind je in page.html.twig.
Themes kunnen andere regio's definiëren. Stable doet dit niet, dus valt terug op de default regio's.

Wil je in je eigen theme specifieke regio's, dan moet je deze in je theme opnieuw definiëren.

**Comment by DamonBaesen** [comment]
Oke dus wat ik wil doen is die twee regios verwijderen en er twee nieuwe maken op andere plaatsen. Dit doe ik dus zelf in mijn eigen info.yml van mij theme dan?

**Comment by guntervs** [comment]
Yes.

**Comment by DamonBaesen** [comment]
Oke top en de andere regios (die er standaard zijn) moet ik dan mee vermelden in mijn eigen info.yml

**Comment by guntervs** [comment]
Als je die wil gebruiken, ja.

**Comment by DamonBaesen** [comment]
oke bedankt. Nog een kleine vraagje: als je de breedte van een bepaalde regio wil aanpassen waar kan je dat doen?

**Comment by guntervs** [comment]
CSS

**Comment by DamonBaesen** [comment]
Ik heb per ongeluk mijn Frontpage (content) view verwijdert waardoor er op mijn frontpage niets meer staat. is er een mogelijkheid om deze standaard view terug te restoren? Op dit moment krijg ik niets meer te zien.

**Comment by guntervs** [comment]
Je bedoelt de view met pad /node?

Views die je hebt verwijderd, kan je niet terug ophalen. Heb je hem effectief verwijderd of een andere als homepage ingesteld?
