### ISSUE TITLE
Body of Image uit {{ content }} aanspreken?

### ISSUE THREAD

**Issue by diederikcraps** [guntervs/weareimd-drupal8#8]
Hey Gunter, 

Wij zijn bezig aan de theming van http://www.webdesignerdepot.com/

Voor de artikels na de 6 promoted artikels staat de bodytekst tussen de titel en de author attributes.
Als ik de {{ content }} in de twig template tussen die twee zet, komt de afbeelding ook mee. 
Is er een mogelijkheid om die {{ content }} in aparte blokjes op te delen, zodat de foto en de body apart kunnen geplaatst worden?

Zo ziet het er momenteel uit:
<img width="704" alt="De huidige situatie" src="https://cloud.githubusercontent.com/assets/9975293/14668965/e57552fa-06e6-11e6-8032-a4e67067fb93.png">

Vriendelijke groeten en alvast bedankt voor je tijd,
Diederik en Leandro

**Comment by guntervs** [comment]
Hoi Diederik,

Ik neem aan dat je een node--*.html.twig template gebruikt?

Je kan in die template rechtstreeks aan je velden door {{ content.field_name }} te gebruiken. Andersom kan je ook alles in content printen behalve een specifiek veld door {{ content|without('field_name') }}

Om te weten welke velden beschikbaar zijn kan je dit met de dump() functie doen bvb. {{ dump(content) }}. Omdat dit te veel informatie geeft, is het interessanter om enkel de array keys te printen {{ dump(content|keys}}

Meer info hierover vind je in de documentatie van de node template zelf:
`* - content: All node items. Use {{ content }} to print them all,
 *   or print a subset such as {{ content.field_example }}. Use
 *   {{ content|without('field_example') }} to temporarily suppress the printing
 *   of a given child element.`

**Comment by diederikcraps** [comment]
Gelukt, bedankt!
<img width="990" alt="screenshot 2016-04-20 11 58 56" src="https://cloud.githubusercontent.com/assets/9975293/14670880/47944998-06ef-11e6-966b-34a2d2f651c6.png">
