### ISSUE TITLE
block views worden niet getoond.

### ISSUE THREAD

**Issue by jorendemaeyer1996** [guntervs/weareimd-drupal8#9]
Gunter,

Wij hebben als opdracht de website [Hodinkee](http://hodinkee.com)

Als wij een block view plaatsen in de region content worden deze niet getoond.

Het probleem is eigenlijk dat wanneer we content aanmaken van de content type story wordt deze altijd getoond op de front page, er wordt eigenlijk geen rekening gehouden met onze blockviews. De content wordt wel getoond met de juiste styling uit onze twig files.

Dus wanneer wij nieuwe blockviews willen plaatsen worden die gewoon niet getoond.

[themes.zip](https://github.com/guntervs/weareimd-drupal8/files/229588/themes.zip)

**Comment by guntervs** [comment]
Hey Joren,

Kan je me screenshots bezorgen van de view settings?

Mij lijkt dat je de homepage niet hebt aangepast, waardoor die nu /node is. /node laat standaard de laatst aangemaakte nodes zien.

**Comment by jorendemaeyer1996** [comment]
Views:
Frontpage
en large articles

<img width="1438" alt="screen shot 2016-04-21 at 15 49 45" src="https://cloud.githubusercontent.com/assets/16215602/14711207/c37ec472-07d8-11e6-8716-71bcc9855b14.png">
<img width="1388" alt="screen shot 2016-04-21 at 15 49 31" src="https://cloud.githubusercontent.com/assets/16215602/14711208/c37ed00c-07d8-11e6-8d1f-bc393560316b.png">

**Comment by guntervs** [comment]
Zet je homepage eens op een andere pagina dan /node via /admin/config/system/site-information

Is het dan nog steeds het geval?

**Comment by jorendemaeyer1996** [comment]
Bedoel je dat we een nieuwe basic page moeten aanmaken en die instellen als
homepage?

**Comment by guntervs** [comment]
Yes.

**Comment by jorendemaeyer1996** [comment]
Het is gelukt, Thanks!

**Comment by guntervs** [comment]
Je blokken stonden wel op de homepage, maar de view van de homepage pushte die naar onderen.
